apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: capstone-external-secret
  namespace: reem-capstone

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore

  target:
    name: capstone-app-secret
    creationPolicy: Owner

  data:
    - secretKey: APP_SECRET
      remoteRef:
        key: cicd-app-secret