apiVersion: v1
kind: ServiceAccount
metadata:
  name: capstone-secrets-sa
  namespace: reem-capstone
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-sa@internship-lab-505207.iam.gserviceaccount.com

---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: reem-capstone
spec:
  provider:
    gcpsm:
      projectID: internship-lab-505207
      auth:
        workloadIdentity:
          clusterProjectID: internship-lab-505207
          clusterLocation: us-central1-a
          clusterName: lab-interns
          serviceAccountRef:
            name: capstone-secrets-sa